### ISSUE TITLE
Having issue with changing the folders.

### ISSUE THREAD

**Issue by ankurparasharpandey** [agolo/logstash-test-runner#4]
"message" => "09-05 20:40:58.723 [pool-16-thread-52] INFO  c.a.c.Controller Try # 1 for doc 789456 feed abcdef took 18 ms",
       "timestamp" => "2018-09-05T20:40:58.723Z"
}
{
    "querytime_ms" => 22,
      "@timestamp" => 2018-09-05T20:40:58.723Z,
       "javaclass" => "c.a.c.Controller",
        "loglevel" => "INFO",
        "@version" => "1",
            "host" => "testing_host",
         "context" => "pool-16-thread-52",
         "message" => "09-05 20:40:58.723 [pool-16-thread-52] INFO  c.a.c.Controller (On try # 1) Doc 789456 clustered into feed abcdef and joined 1 clusters. Total time: 22 ms. Updating DB!",
       "timestamp" => "2018-09-05T20:40:58.723Z"
}
-[2018-09-24T06:15:56,455][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
\./test.sh: line 72: "1537769757" - "1537769741" : syntax error: operand expected (error token is ""1537769757" - "1537769741" ")

TEST SUMMARY
------------
✔ passed - All tests

**Comment by agolomoodysaada** [comment]
Thanks for filing this issue. Can you please clarify the folder changes that were applied?

**Comment by agolomoodysaada** [comment]
This should be resolved by https://github.com/agolo/logstash-test-runner/pull/5
